# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desing.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 670)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #222831;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 570, 660, 90))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.TextInputMessage = QtWidgets.QTextEdit(self.frame_2)
        self.TextInputMessage.setGeometry(QtCore.QRect(10, 9, 551, 71))
        self.TextInputMessage.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TextInputMessage.setFont(font)
        self.TextInputMessage.setMouseTracking(False)
        self.TextInputMessage.setStyleSheet("background-color: #393e46;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;")
        self.TextInputMessage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TextInputMessage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TextInputMessage.setDocumentTitle("")
        self.TextInputMessage.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.TextInputMessage.setObjectName("TextInputMessage")
        self.BtnSendMessage = QtWidgets.QPushButton(self.frame_2)
        self.BtnSendMessage.setGeometry(QtCore.QRect(560, 9, 91, 71))
        self.BtnSendMessage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnSendMessage.setMouseTracking(False)
        self.BtnSendMessage.setStyleSheet("background-color: #00adb5;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;")
        self.BtnSendMessage.setObjectName("BtnSendMessage")
        self.Messages = QtWidgets.QTextEdit(self.centralwidget)
        self.Messages.setGeometry(QtCore.QRect(10, 10, 660, 550))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Messages.setFont(font)
        self.Messages.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Messages.setReadOnly(True)
        self.Messages.setObjectName("Messages")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TextInputMessage.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"><br /></p></body></html>"))
        self.TextInputMessage.setPlaceholderText(_translate("MainWindow", "Введите сообщение"))
        self.BtnSendMessage.setText(_translate("MainWindow", "Отправить"))
